version: '2'
services:
  db:
    environment: 
      - POSTGRES_PASSWORD=alfresco123 
    image: "postgres"
    ports:
      - "5243:5243"

  alfdat:
    image: centos:7
    entrypoint: /bin/bash

  alf:
    environment:
      - DB_CONTAINER_NAME=${COMPOSE_PROJECT_NAME}db_1
    build: ./alf
    ports:
      - "8080:8080"
    links:
       - db:db
    volumes_from:
      - alfdat

  lb:
    build: ./lb
    ports:
      - "80:80"
    links:
       - alf:alf



